---
- name: User | Create User Group
  become: yes
  group:
    name: "{{user.group|default(user.name)}}"
    system: "{{user.system|default(omit)}}"

- name: User | Create User
  become: yes
  user:
    comment: "{{user.comment|default(omit)}}"
    createhome: "{{user.create_home|default(omit)}}"
    group: "{{user.group|default(user.name)}}"
    home: "{{user.home|default(omit)}}"
    shell: "{{user.shell|default(omit)}}"
    name: "{{user.name}}"
    system: "{{user.system|default(omit)}}"
